# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  postgres:
    # see https://hub.docker.com/_/postgres
    # see https://github.com/docker-library/postgres/tree/master/11/bullseye
    image: postgres:14-bullseye
    environment:
      - POSTGRES_PASSWORD=password
    restart: on-failure
  migrate:
    build: .
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=startrek
      - PGUSER=startrek_owner
      - PGPASSWORD=password
    entrypoint:
      - example-migrate-database
  seed:
    build: .
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=startrek
      - PGUSER=startrek_owner
      - PGPASSWORD=password
    command:
      - seed
  run:
    build: .
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=startrek
      - PGUSER=example
      - PGPASSWORD=password
